export const themeKeywords = {
  Cursor: {
    name: 'Cursor',
    foregroundColor: '#282a36',
    backgroundColor: '#f8f8f0',
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  Boolean: {
    name: 'Boolean',
    foregroundColor: '#bd93f9',
    backgroundColor: null,
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  Character: {
    name: 'Character',
    foregroundColor: '#bd93f9',
    backgroundColor: null,
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  ColorColumn: {
    name: 'ColorColumn',
    foregroundColor: null,
    backgroundColor: '#3d3f49',
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  Comment: {
    name: 'Comment',
    foregroundColor: '#6272a4',
    backgroundColor: null,
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  Conditional: {
    name: 'Conditional',
    foregroundColor: '#ff79c6',
    backgroundColor: null,
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  Constant: {
    name: 'Constant',
    foregroundColor: null,
    backgroundColor: null,
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  CursorColumn: {
    name: 'CursorColumn',
    foregroundColor: null,
    backgroundColor: '#44475a',
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  CursorLine: {
    name: 'CursorLine',
    foregroundColor: null,
    backgroundColor: '#44475a',
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  CursorLineNr: {
    name: 'CursorLineNr',
    foregroundColor: '#f1fa8c',
    backgroundColor: '#44475a',
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  Define: {
    name: 'Define',
    foregroundColor: '#ff79c6',
    backgroundColor: null,
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  DiffAdd: {
    name: 'DiffAdd',
    foregroundColor: '#f8f8f2',
    backgroundColor: '#468410',
    bold: true,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  DiffChange: {
    name: 'DiffChange',
    foregroundColor: '#f8f8f2',
    backgroundColor: '#243a5f',
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  DiffDelete: {
    name: 'DiffDelete',
    foregroundColor: '#8b080b',
    backgroundColor: null,
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  DiffText: {
    name: 'DiffText',
    foregroundColor: '#f8f8f2',
    backgroundColor: '#204a87',
    bold: true,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  Directory: {
    name: 'Directory',
    foregroundColor: '#bd93f9',
    backgroundColor: null,
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  ErrorMsg: {
    name: 'ErrorMsg',
    foregroundColor: '#f8f8f0',
    backgroundColor: '#ff79c6',
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  Float: {
    name: 'Float',
    foregroundColor: '#bd93f9',
    backgroundColor: null,
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  FoldColmun: {
    name: 'FoldColmun',
    foregroundColor: '#909194',
    backgroundColor: '#44475a',
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  Folded: {
    name: 'Folded',
    foregroundColor: '#6272a4',
    backgroundColor: '#282a36',
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  Function: {
    name: 'Function',
    foregroundColor: '#50fa7b',
    backgroundColor: null,
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  Identifier: {
    name: 'Identifier',
    foregroundColor: '#8be9fd',
    backgroundColor: null,
    bold: false,
    italic: true,
    underline: false,
    lineThrough: false,
  },
  IncSearch: {
    name: 'IncSearch',
    foregroundColor: '#282a36',
    backgroundColor: '#50fa7b',
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  Keyword: {
    name: 'Keyword',
    foregroundColor: '#ff79c6',
    backgroundColor: null,
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  Label: {
    name: 'Label',
    foregroundColor: '#f1fa8c',
    backgroundColor: null,
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  LineNr: {
    name: 'LineNr',
    foregroundColor: '#909194',
    backgroundColor: '#282a36',
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  MatchParen: {
    name: 'MatchParen',
    foregroundColor: '#ff79c6',
    backgroundColor: null,
    bold: false,
    italic: false,
    underline: true,
    lineThrough: false,
  },
  NonText: {
    name: 'NonText',
    foregroundColor: '#525563',
    backgroundColor: null,
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  Normal: {
    name: 'Normal',
    foregroundColor: '#f8f8f2',
    backgroundColor: '#282a36',
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  Number: {
    name: 'Number',
    foregroundColor: '#bd93f9',
    backgroundColor: null,
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  Operator: {
    name: 'Operator',
    foregroundColor: '#ff79c6',
    backgroundColor: null,
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  Pmenu: {
    name: 'Pmenu',
    foregroundColor: null,
    backgroundColor: null,
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  PmenuSel: {
    name: 'PmenuSel',
    foregroundColor: null,
    backgroundColor: '#44475a',
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  PreProc: {
    name: 'PreProc',
    foregroundColor: '#ff79c6',
    backgroundColor: null,
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  Search: {
    name: 'Search',
    foregroundColor: '#282a36',
    backgroundColor: '#50fa7b',
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  SignColumn: {
    name: 'SignColumn',
    foregroundColor: '#909194',
    backgroundColor: '#44475a',
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  Special: {
    name: 'Special',
    foregroundColor: '#f8f8f2',
    backgroundColor: null,
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  SpecialKey: {
    name: 'SpecialKey',
    foregroundColor: '#525563',
    backgroundColor: null,
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  Statement: {
    name: 'Statement',
    foregroundColor: '#ff79c6',
    backgroundColor: null,
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  StatusLine: {
    name: 'StatusLine',
    foregroundColor: '#f8f8f2',
    backgroundColor: '#64666d',
    bold: true,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  StatusLineNC: {
    name: 'StatusLineNC',
    foregroundColor: '#f8f8f2',
    backgroundColor: '#64666d',
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  StorageClass: {
    name: 'StorageClass',
    foregroundColor: '#8be9fd',
    backgroundColor: null,
    bold: false,
    italic: true,
    underline: false,
    lineThrough: false,
  },
  String: {
    name: 'String',
    foregroundColor: '#f1fa8c',
    backgroundColor: null,
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  Tag: {
    name: 'Tag',
    foregroundColor: '#ff79c6',
    backgroundColor: null,
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  Title: {
    name: 'Title',
    foregroundColor: '#f8f8f2',
    backgroundColor: null,
    bold: true,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  Todo: {
    name: 'Todo',
    foregroundColor: null,
    backgroundColor: '#6272a4',
    bold: true,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  Type: {
    name: 'Type',
    foregroundColor: '#8be9fd',
    backgroundColor: null,
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  Underlined: {
    name: 'Underlined',
    foregroundColor: null,
    backgroundColor: null,
    bold: false,
    italic: false,
    underline: true,
    lineThrough: false,
  },
  VertSplit: {
    name: 'VertSplit',
    foregroundColor: '#64666d',
    backgroundColor: '#64666d',
    bold: true,
    italic: false,
    underline: true,
    lineThrough: false,
  },
  Visual: {
    name: 'Visual',
    foregroundColor: null,
    backgroundColor: '#44475a',
    bold: false,
    italic: false,
    underline: true,
    lineThrough: false,
  },
  WarningMsg: {
    name: 'WarningMsg',
    foregroundColor: '#f8f8f0',
    backgroundColor: '#ff79c6',
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  TabLine: {
    name: 'TabLine',
    foregroundColor: '#666666',
    backgroundColor: '#282a36',
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  TabLineFill: {
    name: 'TabLineFill',
    foregroundColor: '#333333',
    backgroundColor: '#282a36',
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
  TabLineSel: {
    name: 'TabLineSel',
    foregroundColor: '#FFFFFF',
    backgroundColor: '#282a36',
    bold: false,
    italic: false,
    underline: false,
    lineThrough: false,
  },
};
